version: "3"

services:
  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    depends_on: 
      - db
    command: npm test
