version: "3"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:5432
    command: [ "/bin/sh", "-c", '/wait && npm test' ]
